### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Nik6511** [Nik6511/StudentRegistration#1]
This project is not complete. It's just a test project

**Comment by bitwizard25** [comment]
hi, can we talk a little bit more about this project brother I am interested to collaborate with u on this project?

her is my email:- 
rbworkmail3@gmail.com       
   

if u   are  interested  to plz... feel  to email me brother
thank you  have a  good day brother

**Comment by Nik6511** [comment]
Thanks for showing interest brother for this was just a test project.  I am not working on this anymore. If I work on some cool projects in the future I will let you know
